apiVersion: v1
kind: Service
metadata:
    name: library
spec:
    type: LoadBalancer
    ports:
    - port: 20987 
    selector:
        app: library
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: library
  name: library
  namespace: default
spec:
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - image: shipu/library:1.0
        imagePullPolicy: Always
        name: library
        ports:
         - containerPort: 20987
        command: ["/library/library"]
        #args: ["HOSTNAME", "KUBERNETES_PORT"]
